# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\self.Users\ngois\Desktop\QT\table'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import Qt, pyqtSignal
from PyQt5 import QtCore, QtGui, QtWidgets
from functools import partial
from card import Card
from alert import Alert

class QLabel_alterada(QtWidgets.QLabel):
    def __init__(self, parent=None):
        super(QLabel_alterada, self).__init__(parent)
    clicked=QtCore.pyqtSignal()

    def setCount(self, count):
        self.count = count

    def setCard(self, card):
        self.card = card

    def mousePressEvent(self, ev):
        self.clicked.emit()
class Ui_Table(object):
    # def __init__(self):
    #     self.MainWindow = QtWidgets.QMainWindow()
    #     self.setupUi(self.MainWindow)
    #     self.MainWindow.show()

    def __init__(self, user,thread):
        self.thread = thread
        self.user = user
        self.size = 1
        self.MainWindow = QtWidgets.QMainWindow()
        self.MainWindow.setWindowTitle(self.user.name)
        self.thread.notify.disconnect()
        self.thread.notify.connect(self.receiveMsg)
        self.setupUi(self.MainWindow)
        self.MainWindow.show()
        user.sendMsg("list")

    def chat(self):
        self.user.sendMsg("chatRoom,"+self.lineEdit.text())
        self.lineEdit.clear()

    def skip(self):
        self.turn(False)
        self.user.sendMsg("skip")

    def sortCard(self,e):
        return ((e.num*10)+e.suit)

    def play(self,msg):
        msg = "play"
        self.temp.sort(key=self.sortCard)
        for x in self.temp:
            msg+=","+x.show()
        self.user.sendMsg(msg)
        self.turn(False)

    def setLblTemp(self,temp):
        for x in self.lblTemp:
            x.hide()
        # temp = self.temp
        center = 6
        start = int(center - len(temp)/2)
        for x in range(start,start+len(temp)):
            self.lblTemp[x].setPixmap(QtGui.QPixmap(":/newPrefix/cards/"+temp[x-start].convert()+".gif"))
            self.lblTemp[x].show()

    def setLabel(self):
        for x in self.lblCards:
            x.hide()
        center = 6
        start = int(center - len(self.user.cards)/2)
        for x in range(start,start+len(self.user.cards)):
            card = self.user.cards[x-start]
            self.lblCards[x].setCard(Card(card.num,card.suit))
            self.lblCards[x].setPixmap(QtGui.QPixmap(":/newPrefix/cards/"+self.lblCards[x].card.convert()+".gif"))
            self.lblCards[x].show()

    def getCard(self, num, suit):
        card = Card(num,suit)
        self.user.addCard(card)
    def finishRelease(self):
        self.user.cards.sort(key=self.sortCard)
        for x in range(0,len(self.user.cards)):
            print(self.user.cards[x].convert())
            self.lblCards[x].setPixmap(QtGui.QPixmap(":/newPrefix/cards/"+self.user.cards[x].convert()+".gif"))
            self.lblCards[x].setCard(self.user.cards[x])
            self.lblCards[x].show()

    def finish(self,msg):
        msg.pop(0)
        m = ""
        for x in range(len(msg)):
            m+= str(x)+". "+msg[x]+"\n"

    def leave(self):
        self.user.sendMsg("leave")
        del self.MainWindow
        Ui_MainWindow(self.user)


    def turn(self,bl):
        self.pushButton.setVisible(bl)
        self.pushButton_2.setVisible(bl) 

    def  removeCard(self):
        for x in self.temp:
            self.user.cards.remove(x)
        self.setLabel()
        
    def changeCOD(self,msg):
        msg.pop(0)
        temp = []
        if len(msg) == 0: return
        for x in msg:
            c = x.split("-")
            temp.append(Card(int(c[0]),int(c[1])))
        self.setLblTemp(temp) 

    def startGame(self):
        self.user.cards.clear()
        self.temp.clear()
        self.turn(False)
        for x in self.lblTemp:
            x.hide()
        for x in self.lblCards:
            x.setGeometry(QtCore.QRect(x.x(), 640, 73, 97))
            x.setCount(0)
        for x in self.users:
            if x[0].text() != "none":
                x[2].setText("13")
                x[2].show()
                x[3].show()

    def newJoin(self,msg):
        msg.pop(0)
        for x in range(len(self.users)):
            if self.users[x][0].text() == "none":
                self.users[x][0].setText(msg[0])
                self.showUser(x)
                break

    def list(self,msg):
        msg.pop(0)
        #pl1,pl2,me,none
        count = 0
        p1 = []
        p2 = []
        users = []
        for x in msg:
            if x == "me": break
            count+=1
            p1.append(x)
        for x in range(count+1,len(msg)):
            p2.append(msg[x])
        users.extend(p2)
        users.extend(p1)
        print(users)
        for x in range(len(self.users)):
            if users[x] != "none":
                self.users[x][0].setText(users[x])
                self.showUser(x)


    def showUser(self,x):
        self.users[x][0].show()
        self.users[x][1].show()

    def hideUser(self,msg):
        msg.pop(0)
        for x in self.users:
            if msg[0] == x[0]:
                for p in x: p.hide()


    def receiveMsg(self,message):
        msg = message.split(',')
        if msg[0] == "chatRoom":
            self.insertText(msg[2]+": "+msg[1])
        elif msg[0] == "release":
            self.getCard(int(msg[1]),int(msg[2]))
        elif msg[0] == "finishRelease":
            self.finishRelease()
        elif msg[0] == "play":
            self.changeCOD(msg)
        elif msg[0] == "start":
            self.startGame()
        elif msg[0] == "move":
            self.turn(True)
        elif msg[0] == "legal":
            self.turn(False)
            self.removeCard()
            self.unChoose()
        elif msg[0] == "move":
            self.turn(True)
        elif msg[0] == "notLegal":
            Alert("đánh bài không hợp lệ")
            self.turn(True)
        elif msg[0] == "lose": 
            self.turn(False)
            Alert("bạn đã thua")
        elif msg[0] == "win":  
            self.turn(False)
            Alert("bạn đã chiến thắng")
        elif msg[0] == "finish":
            self.finish(msg)
        elif msg[0] == "newJoin":
            self.newJoin(msg)
        elif msg[0] == "list":
            self.list(msg)
        elif msg[0] == "leave":
            self.hideUser(msg)
        elif msg[0] == "updateNum":
            self.updateNum(msg)


    def updateNum(self,msg):
        msg.pop(0)
        for x in self.users:
            if x[0].text() == msg[0]:
                x[2].setText(msg[1])


    def choose(self,label):
        if label.count == 0:
            label.setGeometry(QtCore.QRect(label.x(), 615, 73, 97))
            label.setCount(1)
            self.temp.append(label.card)
        else: 
            label.setGeometry(QtCore.QRect(label.x(), 640, 73, 97))
            label.setCount(0)
            self.temp.remove(label.card)
    def unChoose(self):
        for x in self.lblCards:
            if x.count != 0:
                x.setGeometry(QtCore.QRect(x.x(), 640, 73, 97))
                x.setCount(0)
        self.temp.clear()

    def setupUi(self, MainWindow):
        MainWindow.resize(1345, 793)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(201, 126))
        self.centralwidget.setMaximumSize(QtCore.QSize(1397, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.users = []
        self.player = []
        user2 = [] #[name,avt,num,back]
        user3 = []
        user4 = []
        self.lblTemp = []
        self.lblCards = []
        self.temp = []
        x = 310
        for i in range(0,13):
            label = QLabel_alterada(self.centralwidget)
            label.setGeometry(QtCore.QRect(x, 640, 73, 97))
            # label.setPixmap(QtGui.QPixmap(":/newPrefix/cards/1c.gif"))
            label.setScaledContents(False)
            label.setCount(0)
            label.setCursor(Qt.PointingHandCursor)
            label.clicked.connect(partial(self.choose,label))
            self.lblCards.append(label)
            x+=50
            label.raise_()
            
        x = 310
        for i in range(0,13):
            label = QtWidgets.QLabel(self.centralwidget)
            label.setGeometry(QtCore.QRect(x, 320, 73, 97))
            # label.setPixmap(QtGui.QPixmap(":/newPrefix/cards/1d.gif"))
            label.setScaledContents(True)
            label.raise_()
            x+=50
            self.lblTemp.append(label)
        label_14 = QtWidgets.QLabel(self.centralwidget)
        label_14.setGeometry(QtCore.QRect(150, 320, 73, 97))
        label_14.setPixmap(QtGui.QPixmap(":/newPrefix/cards/b.gif"))
        label_14.setScaledContents(True)
        label_30 = QtWidgets.QLabel(self.centralwidget)
        label_30.setGeometry(QtCore.QRect(160, 350, 51, 41))
        label_30.setFont(font)
        label_30.setStyleSheet("QLabel{\n"
"    background-color: #ECAB53;\n"
"    color: #FFF\n"
"}")

        label_30.setAlignment(QtCore.Qt.AlignCenter)
        lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        lineEdit_2.setGeometry(QtCore.QRect(10, 425, 131, 51))
        lineEdit_2.setFont(font)
        lineEdit_2.setStyleSheet("QLineEdit{\n"
"    border-radius: 20px;\n"
"}")
        lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        lineEdit_2.setReadOnly(True)
        label_34 = QtWidgets.QLabel(self.centralwidget)
        label_34.setGeometry(QtCore.QRect(14, 319, 121, 101))
        label_34.setStyleSheet("QLabel{\n"
"    border-radius: 50px;\n"
"}")
        label_34.setPixmap(QtGui.QPixmap(":/newPrefix/cards/avatar4.jpg"))
        label_34.setScaledContents(True)
        user2.append(lineEdit_2)
        user2.append(label_34)
        user2.append(label_30)
        user2.append(label_14)
        self.users.append(user2)

        label_29 = QtWidgets.QLabel(self.centralwidget)
        label_29.setGeometry(QtCore.QRect(630, 20, 73, 97))
        label_29.setStyleSheet("background-image: url(:/newPrefix/cards/1c.gif)")
        label_29.setPixmap(QtGui.QPixmap(":/newPrefix/cards/b.gif"))
        label_29.setScaledContents(True)
        lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        lineEdit_4.setGeometry(QtCore.QRect(493, 127, 131, 51))
        lineEdit_4.setFont(font)
        lineEdit_4.setStyleSheet("QLineEdit{\n"
"    border-radius: 20px;\n"
"}")
        lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        lineEdit_4.setReadOnly(True)
        label_31 = QtWidgets.QLabel(self.centralwidget)
        label_31.setGeometry(QtCore.QRect(640, 50, 51, 41))
        label_31.setFont(font)
        label_31.setStyleSheet("QLabel{\n"
"    background-color: #ECAB53;\n"
"    color: #FFF\n"
"}")
        label_31.setAlignment(QtCore.Qt.AlignCenter)
        label_36 = QtWidgets.QLabel(self.centralwidget)
        label_36.setGeometry(QtCore.QRect(496, 20, 121, 101))
        label_36.setStyleSheet("QLabel{\n"
"    border-radius: 50px;\n"
"}")
        label_36.setPixmap(QtGui.QPixmap(":/newPrefix/cards/avatar2.jpg"))
        label_36.setScaledContents(True)
        user3.append(lineEdit_4)
        user3.append(label_36)
        user3.append(label_31)
        user3.append(label_29)
        self.users.append(user3)

        label_15 = QtWidgets.QLabel(self.centralwidget)
        label_15.setGeometry(QtCore.QRect(1118, 320, 73, 97))
        label_15.setPixmap(QtGui.QPixmap(":/newPrefix/cards/b.gif"))
        label_15.setScaledContents(True)
        label_37 = QtWidgets.QLabel(self.centralwidget)
        label_37.setGeometry(QtCore.QRect(1128, 350, 51, 41))
        label_37.setFont(font)
        label_37.setStyleSheet("QLabel{\n"
"    background-color: #ECAB53;\n"
"    color: #FFF\n"
"}")
        label_37.setAlignment(QtCore.Qt.AlignCenter)
        lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        lineEdit_5.setGeometry(QtCore.QRect(1203, 425, 131, 51))
        lineEdit_5.setFont(font)
        lineEdit_5.setStyleSheet("QLineEdit{\n"
"    border-radius: 20px;\n"
"}")
        lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        lineEdit_5.setReadOnly(True)
        

        label_35 = QtWidgets.QLabel(self.centralwidget)
        label_35.setGeometry(QtCore.QRect(1208, 320, 121, 101))
        label_35.setStyleSheet("QLabel{\n"
"    border-radius: 50px;\n"
"}")
        label_35.setPixmap(QtGui.QPixmap(":/newPrefix/cards/avatar3.jpg"))
        label_35.setScaledContents(True)
        
        user4.append(lineEdit_5)
        user4.append(label_35)
        user4.append(label_37)
        user4.append(label_15)
        self.users.append(user4)

        label_33 = QtWidgets.QLabel(self.centralwidget)
        label_33.setGeometry(QtCore.QRect(17, 585, 121, 101))
        label_33.setStyleSheet("QLabel{\n"
"    border-radius: 50px;\n"
"}")
        label_33.setPixmap(QtGui.QPixmap(":/newPrefix/cards/avatar.jpg"))
        label_33.setScaledContents(True)
        lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        lineEdit_3.setGeometry(QtCore.QRect(14, 690, 131, 51))
        lineEdit_3.setFont(font)
        lineEdit_3.setStyleSheet("QLineEdit{\n"
"    border-radius: 20px;\n"
"}")
        lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        lineEdit_3.setReadOnly(True)
        self.player.append(lineEdit_3)
        self.player.append(label_33)

     
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(410, 560, 131, 51))
        self.pushButton.setFont(font)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(770, 560, 131, 51))
        self.pushButton_2.setFont(font)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(840, 220, 391, 41))
        # self.lineEdit.returnPressed.connect(self.type)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(840, 10, 491, 201))
        self.textEdit.setStyleSheet("QTextEdit{\n"
"self.textEdit.setReadOnly(True)\n"
"}")
        self.textEdit.setReadOnly(True)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 20, 131, 51))
        self.pushButton_3.setFont(font)

        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(620, 560, 81, 51))
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("")

        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(1250, 220, 81, 41))
        self.pushButton_9.setFont(font)


        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        # self.label_30.setText(_translate("MainWindow", "1a"))
        self.pushButton.setText(_translate("MainWindow", "Bỏ lượt"))
        self.pushButton_2.setText(_translate("MainWindow", "Đánh"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Rời phòng"))
        self.pushButton_4.setText(_translate("MainWindow", "15"))
        for x in self.users:
            x[0].setText("none")
            for obj in x:
                obj.hide()
        self.player[0].setText(_translate("MainWindow", self.user.name))
        self.turn(False)
        # self.showBtn(False)
        # self.users[2][3].setText(_translate("MainWindow", "1b"))
        # self.label_37.setText(_translate("MainWindow", "1c"))
        # self.pushButton_9.setText(_translate("MainWindow", "Gửi"))
        # self.lineEdit_2.setText(_translate("MainWindow", "UserName1"))
        # self.lineEdit_3.setText(_translate("MainWindow", "UserName2"))
        # self.lineEdit_4.setText(_translate("MainWindow", "UserName3"))
        # self.lineEdit_5.setText(_translate("MainWindow", "UserName4"))
        self.pushButton.clicked.connect(self.skip)
        self.pushButton_2.clicked.connect(self.play)
        self.lineEdit.returnPressed.connect(self.chat)
        self.pushButton_3.clicked.connect(self.leave)

    def showBtn(self,x):
        self.pushButton.setVisible(x)
        self.pushButton_2.setVisible(x)
        self.pushButton_4.setVisible(x)

    def type(self):
        self.insertText(self.lineEdit.text())
        self.lineEdit.clear()

    def insertText(self,msg):
        self.textEdit.append(msg+"\n")
import cards_rc


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     ui = Ui_Table()
#     sys.exit(app.exec_())
